import { MD3LightTheme, type MD3Theme } from 'react-native-paper';

import { colors, radius } from '@/constants/theme';

export const paperTheme: MD3Theme = {
  ...MD3LightTheme,
  dark: false,
  roundness: radius.md,
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.primary,
    primaryContainer: colors.primarySoft,
    secondary: colors.accent,
    secondaryContainer: colors.accentSoft,
    tertiary: colors.success,
    tertiaryContainer: colors.successSoft,
    surface: colors.card,
    surfaceVariant: colors.background,
    surfaceDisabled: colors.border,
    background: colors.background,
    error: colors.danger,
    errorContainer: colors.dangerSoft,
    onPrimary: colors.white,
    onPrimaryContainer: colors.primaryDark,
    onSecondary: colors.white,
    onSecondaryContainer: colors.accent,
    onTertiary: colors.white,
    onTertiaryContainer: colors.success,
    onSurface: colors.text,
    onSurfaceVariant: colors.textSecondary,
    onSurfaceDisabled: colors.textMuted,
    onError: colors.white,
    onErrorContainer: colors.danger,
    onBackground: colors.text,
    outline: colors.borderStrong,
    outlineVariant: colors.border,
    inverseSurface: colors.text,
    inverseOnSurface: colors.white,
    inversePrimary: colors.primarySoft,
    shadow: colors.text,
    scrim: colors.text,
    backdrop: colors.overlay,
    elevation: {
      ...MD3LightTheme.colors.elevation,
      level0: 'transparent',
      level1: colors.card,
      level2: colors.card,
      level3: colors.card,
      level4: colors.card,
      level5: colors.card,
    },
  },
};
